### ISSUE TITLE
Problem with Intersecting Open Records

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#585] opened 2016-02-11 23:48 UTC
This really shouldn't work:

```
type r is {int a, ...}
type r1 is {int a, int b, ...}
type r2 is {int a, bool b, ...}

public export method test():
    r1 x = (r1) {a:42, b:0}
    r2 y = (r2) {a:42, b:true}
    &r px = new(r) x
    &r py = new(r) y
    *px = *py
    r x1 = *px
    if x1 is r1:
        int z = x1.b
```

It reports

```
branch always taken
    if x1 is r1:
       ^^^^^^^^
```

which makes me assume that `x1` is statically treated as `r1`.
When the program is able to reach the last line, we must get a type error in `int z = x1.b` as it would assign the `bool` from within `py` to the local variable `int` `z`.

**Comment by DavePearce** [comment] 2016-02-12 00:57
Hmmm, so this doesn't seem to be a problem with the `new` operator, or with flow typing.  Rather it seems to be a problem computing the intersection of two open records for the false branch.  Specifically, we have that:

```
{int a,...} & !{int a,int b,...} = void
```
The problem is that there's no way to describe the *absence* of a type from an open record.  We want to say that the result is `{int a, ...}` but where `...` cannot be `int`.  For example, `{int a, !int b, ...}` is not exactly what we want as that is the set of all records with a field `b`.

Looking back through past issues, I notice that in #46 the curious comment:

> Open records are essentially working, but there are a number of problems with intersecting them.

So, this looks like an unresolved problem.

**Comment by DavePearce** [comment] 2016-02-12 00:59
@SebastianS90 I'm not going to investigate this further now.  But, you should a variant of the above as a new test case and then mark it ignored against this issue.

**Comment by DavePearce** [comment] 2017-09-18 04:40
This is now fixed.

**Closed by DavePearce** 2017-09-18 04:40 UTC
Labels: Bug, Useful
