### ISSUE TITLE
Flow Typing and "is" usage

### ISSUE THREAD

**Issue by BaptP** [Whiley/WhileyCompiler#721] opened 2017-05-04 21:48 UTC
Whereas the following funcion is rejected by the typer :
```ocaml
function h(int|bool x) -> bool:
    return x
```

Adding one line make it accepted : 
```ocaml
function h(int|bool x) -> bool:
    bool a = x is bool
    return x
```

**Comment by phase** [comment] 2017-05-05 01:05
That seems valid. The first is a type error while the latter asserts x is a bool and will throw a runtime error if it isn't. (if I am guessing correctly)

**Comment by bambinella** [comment] 2017-05-05 06:33
On Thu, May 4, 2017 at 11:48 PM, BaptP <notifications@github.com> wrote:

> Adding one line make it accepted :
>
> function h(int|bool x) -> bool:
>     bool a = x is bool
>     return x
>
>
Didn't pass on whileylabs: http://whileylabs.com/

Ola.

**Comment by DavePearce** [comment] 2017-05-05 07:09
Hey Ola,

Yes, it does pass on whileylabs if you disable verification (and, hence, only the type checker is in play).

It looks to be some kind of bug related to how flow typing is handled in `wyc.builder.FlowTypeChecker` ... needs investigation.

**Comment by DavePearce** [comment] 2017-05-05 07:12
Hey Phase,

> That seems valid. The first is a type error while the latter asserts x is a bool and will throw a runtime error if it isn't. (if I am guessing correctly)

No, it doesn't even use the variable `a` so it's not even asserting it!  The problem is that the flow type checker is assuming for some reason `x is bool` holds after the statement which isn't necessarily true ... ?

**Comment by DavePearce** [comment] 2017-09-18 04:22
This is now fixed in the latest `develop` snapshot.

**Closed by DavePearce** 2017-09-18 04:22 UTC
Labels: Bug, Useful
