### ISSUE TITLE
Update of dereferenced pointer: Internal failure, Invalid type for Update

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#551] opened 2015-12-21 04:16 UTC
The following program causes a compilation failure:
````
method m(&int x):
    *x = 1
````

> Internal failure, Invalid type for Update

The message could come from [wyil.lang.Codes.UpdateIterator.next()](https://github.com/Whiley/WhileyCompiler/blob/975fea2c8533fac223de31bcac68821e6d74fede/modules/wyil/src/wyil/lang/Codes.java#L2276)

The [swap example in WhileyLanguageSpecification](https://github.com/Whiley/WhileyDocs/blob/master/WhileyLanguageSpecification/examples/ch4/eg_12.whiley) does not compile due to this issue.

**Comment by DavePearce** [comment] 2015-12-22 21:19
This bug is a problem in the <code>Whiley2Java</code> backend, as the code compiles fine from <code>wyc</code> directly.

**Comment by DavePearce** [comment] 2015-12-22 21:21
Ok, this is also a duplicate of issue of #428.  I'll close that one and keep this one open for now, since Matt is no longer involved.

**Comment by DavePearce** [comment] 2015-12-23 00:05
Fix for this issue is now merged into <code>develop</code> and is scheduled to land in the next release.

**Closed by DavePearce** 2015-12-23 00:05 UTC
Labels: Bug, Important, WYJC
