### ISSUE TITLE
Calling methods in functions using lambdas

### ISSUE THREAD

**Issue by DrewStratford** [Whiley/WhileyCompiler#567] opened 2016-01-15 00:14 UTC
Using the following code we are able to call the method foo inside the function f by passing it as a lambda.

    import whiley.lang.System
    
    type Meth is method (System.Console) -> int
    
    function f (Meth ms, System.Console c) -> int:
        return ms(c) + 11
        
    method foo (System.Console c) -> int:
        c.out.println_s("this is in a method")
        return 10
    
    method main(System.Console console):
        Meth m = &(System.Console c -> c.out.println_s("test"))
        
        console.out.println_s("Hello World")
        int i = f (&foo, console)
        int ii = i+1
        
Which when run outputs:

    Hello World
    this is in a method

However if we pass m to f instead of &foo we get the following null pointer exception:

    Hello World
    Exception in thread "main" java.lang.NullPointerException
    	at methodTest.f$_9dF5u1Fc_V5$o5$_0$S$V5$j0$O$F4$_0kR$F60FI$J5$o0$Ph3J0Vv$$C$H2$q$cB$m2VM$VC$12$r$sB$T0Vd$7E$a2$u$cB$Pv$N7$T2$r$ND$T2$q$cg2(./methodTest.whiley)
    	at methodTest.main$2Ab737oHF4$i2$o$7C$N2Vm$7E$T0$q$7B$R2Vn$s4$a1Vw$ND$c2Vm$ch2VW$sC$R2Vt$sC$N2Vm1(./methodTest.whiley)
    	at methodTest.main(./methodTest.whiley)

**Comment by DavePearce** [comment] 2016-01-19 02:04
Hi Drew,

Sorry for the slow reply.  Ok, I knowledge this bug exists in v0.3.37.  I'm not really sure what the issue is though, and the error has changed in my latest snapshot on the <code>develop</code> branch.  When I've finished my latest round of updates for the next version (should be soon), I'll come back to this and see what's going on.

Anyhow, can I ask what you're using Whiley for?  Let me know if I can help in anyway ...

**Comment by DrewStratford** [comment] 2016-01-19 05:24
Hi David, 

I've looked through the code and I believe the issue is in the checkFunctionPure method in
modules/wyil/src/wyil/checks/ModuleCheck.java.

The function checks that any code of type Codes.Invoke is not a method, however it does not check for code of type Codes.Invoke (which I assume that the problematic method is an instance of).

I have altered the method as follows:

	protected void checkFunctionPure(CodeBlock.Index parent, CodeBlock block, AttributedCodeBlock root) {
		for (int i = 0; i != block.size(); ++i) {
			Code code = block.get(i);
			CodeBlock.Index index = new CodeBlock.Index(parent,i);
			if(code instanceof Codes.Invoke && ((Codes.Invoke)code).type() instanceof Type.Method) {
				// internal message send
				syntaxError(errorMessage(METHODCALL_NOT_PERMITTED_IN_FUNCTION), filename, root.attribute(index, SourceLocation.class));

				// added check for IndirectInvoke
			} else if (code instanceof Codes.IndirectInvoke && ((Codes.IndirectInvoke)code).type() instanceof Type.Method) {
				// internal message send
				syntaxError(errorMessage(METHODCALL_NOT_PERMITTED_IN_FUNCTION), filename, root.attribute(index, SourceLocation.class));
			} else if ...
		}
	}

This gives the expected compiler error although I have not tested it thoroughly.


As for my use of the language I'm just playing around with it. Last year I was in one of your 200 level swen courses that used Whiley and I'm interested in how the language works.

**Comment by DavePearce** [comment] 2016-01-19 23:13
Hi Drew,

Ah, OK ... sorry I should have recognised your name from SWEN224!  Great to hear that you're interested in looking at the code.

So, yes I see what you've done there ... it makes sense.  You should set up a pull request, and I'll merge it in.  Ideally, make your change against the <code>develop</code> branch and then set up the pull request.  

Also, let me know if I can help you with understanding the compiler.  We could even meet for coffee sometime, or to talk stuff over on the whiteboard.  For example, even getting it setup properly under Eclipse is a pain ...

D

**Comment by DavePearce** [comment] 2016-01-19 23:14
Oh, I should add that you need to "sign" the contributors agreement first as well.  Look in the CONTRIBUTORS files for info about that.

**Comment by DavePearce** [comment] 2016-01-22 01:24
Resolved with Pull Request 570 --- https://github.com/Whiley/WhileyCompiler/pull/570

**Closed by DavePearce** 2016-01-22 01:24 UTC
Labels: Bug, Useful, WYJC
