### ISSUE TITLE
Type test against reference types unsafe

### ISSUE THREAD

**Issue by SebastianS90** [Whiley/WhileyCompiler#630] opened 2016-04-20 08:23 UTC
I hope that it is not again a duplicate, but the search function didn't find anything similar.

Type tests currently allow to test against reference types. Together with flow typing we can attempt to break memory safety. Consider the following program:

```
method main(whiley.lang.System.Console console):
    &(int|bool) p_intbool = new (int|bool)true
    &bool p_bool = new false
    &(int|bool) alias = p_intbool
    if (p_intbool is &bool):
        p_bool = p_intbool
    *alias = 3
    bool b = *p_bool
```

The main goal of this program is to store an integer at the destination of a `&bool`. It compiles with the current version of whiley.

The alias is needed, as an assignment directly to `p_intbool` results in an internal failure at compile time (some null pointer exception in flow type checker).

The program compiles. On execution, it throws this exception:

```
Exception in thread "main" java.lang.ClassCastException: java.math.BigInteger cannot be cast to wyjc.runtime.WyBool
    at test.main$1AY7P8c1$r0$P$Z5$g0FO$Z6$j$$Q$35$i0kO$w1$I0FT$B6$o0FO$oq0kF$w5$i0kR$w5$g0FOz(./test.whiley)
    at test.main(./test.whiley)
```

Luckily the JVM saves us from corrupting memory. But this is definitely not ideal. In my opinion it should not be possible to do a type test against a reference. At least the flow type checker must not set the type accordingly, but that renders type tests against references useless so we can forbid them in the first place.

The correct way to test a reference type is to read the data first: `int|bool data = *p_intbool`. Then you can do a type test against `data`.

By the way, my lifetimes extension currently unintentionally "solves" that issue by throwing a nullpointer exception at compile time for type tests against references.

**Comment by DavePearce** [comment] 2016-04-20 08:26
Oh dear ... that's definitely a problem.  You see to be finding lots recently!

Also, don't worry too much about whether the issue is a duplicate.  It's hard to find them ... I just have the advantage of having opened most of them, so I know them pretty well ;)

**Comment by SebastianS90** [comment] 2016-04-20 08:29
It is easy to find issues when writing a thesis about whiley. I come up with a lot of examples demonstrating whileys features. I try to run my examples and then run into problems :wink:

**Comment by SebastianS90** [comment] 2016-04-20 08:32
But regarding the topic, any reasons to not forbid type tests against references?

**Comment by SebastianS90** [comment] 2016-04-22 00:50
Probably it's also unsafe to test against records that contain references. You could extraxt the downcasted (through flow typing) reference afterwards.

And casting with references is also problematic, but that is probably already forbidden by variant subtyping (#583)

And it is worth thinking about whether function/method types should be allowed to appear in type tests.

**Comment by DavePearce** [comment] 2017-09-18 04:35
This is now fixed in `develop`.  The compiler reports this error:
```
./test.whiley:5: incomparable operands: &((int|bool)) and &bool
    if (p_intbool is &bool):
        ^^^^^^^^^^^^^^^^^^
```

**Closed by DavePearce** 2017-09-18 04:35 UTC
